doctrine:
    dbal:
        driver: 'pdo_mysql'
        server_version: '5.7'

        charset: utf8mb4
        default_table_options:
            charset: utf8mb4
            collate: utf8mb4_unicode_ci

        url: '%env(resolve:DATABASE_URL)%'

        types:
            recipe_name: App\Infrastructure\DBAL\Value\RecipeName
            portion: App\Infrastructure\DBAL\Value\Portion
            duration: App\Infrastructure\DBAL\Value\Duration
            complexity: App\Infrastructure\DBAL\Value\Complexity
            ingredient_name: App\Infrastructure\DBAL\Value\IngredientName

    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: php
                dir: '%kernel.project_dir%/src/Infrastructure/Entity'
                prefix: 'App\Domain\Entity'
                alias: App
