security:
    encoders:
        App\Infrastructure\Entity\User:
            id: 'App\Infrastructure\Security\Encoder\DomainEncoder'

    providers:
        your_custom_user_provider:
            id: App\Infrastructure\Security\UserProvider

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern: ^/api/login
            anonymous: true
            stateless: true
            json_login:
                check_path: /api/login
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure

        api:
            pattern: ^/api
            anonymous: true
            stateless: true
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator

    access_control:
        - { path: ^/api/users, methods: POST, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    # - { path: ^/profile, roles: ROLE_USER }
