openapi: 3.0.0
info:
  title: 'Food API'
  version: 1.0.0
servers:
  -
    url: 'http://127.0.0.1/'
    description: Default
paths:
  /recipes:
    get:
      summary: 'Get the list of the validated recipes'
      operationId: 'App\Infrastructure\Controller\Recipes\ReadAllAction::__construct'
      responses:
        '200':
          description: success
components:
  schemas:
    Recipe:
      properties:
        id:
          type: uuid
        name:
          type: string
        portion:
          description: 'Number of people the recipe is made for'
          type: integer
        duration:
          description: 'Duration in minute'
          type: integer
        complexity:
          description: 'Complexity between 0 and 5'
          type: integer
      type: object
