root:
    path: /
    controller: App\Infrastructure\Controller\RootAction::handle

login:
    path: /api/login
    controller: App\Infrastructure\Controller\LoginAction::handle

api:
    resource: routes/api.yml
    prefix: /api/
