root:
    path: /
    controller: App\Infrastructure\Controller\RootAction::handle

login_check:
    path: /api/login_check
    controller: App\Infrastructure\Controller\LoginAction::handle

recipes:
    resource: routes/recipes.yml

users:
    resource: routes/users.yml
