root:
    path: /
    controller: App\Infrastructure\Controller\RootAction::handle

login:
    path: /api/login
    controller: App\Infrastructure\Controller\LoginAction::handle

recipes:
    resource: routes/recipes.yml
    prefix: /api/

users:
    resource: routes/users.yml
    prefix: /api/

profile:
    resource: routes/profile.yml
    prefix: /api/