parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

#    App\:
#        resource: '../src/*'
#        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    App\Infrastructure\:
        resource: '../src/Infrastructure/*'
        exclude: '../src/{Entity,Migrations}'

    App\Infrastructure\Controller\:
        resource: '../src/Infrastructure/Controller/*'
        tags: ['controller.service_arguments']

